Update patch set 1
Patch Set 1:

> I don't understand the problem. Where is the actual bug? In ansible
 > or in kolla? What ansible fact replaces all these things and why
 > does it work with OSA?

I didn't open a bug because this is a requirement for kolla, given that if it's not change it, its tasks fail like this:

TASK [memcached : Copying over config.json files for services] **********************************************************************************************************************
task path: /usr/local/share/kolla-ansible/ansible/roles/memcached/tasks/config.yml:13
failed: [opnfv] (item=memcached) => {
    "changed": false,
    "item": "memcached",
    "msg": "AnsibleUndefinedVariable: {{ hostvars[inventory_hostname]['ansible_' + api_interface]['ipv4']['address'] }}: 'dict object' has no attribute 'ipv4'"
}
        to retry, use: --limit @/usr/local/share/kolla-ansible/ansible/site.retry
 
PLAY RECAP **************************************************************************************************************************************************************************
opnfv                      : ok=6    changed=0    unreachable=0    failed=1

Maybe using names with underscores instead of dashes can benefit both installers.

Patch-set: 1